name: beckybooker
favicon: null
layout_spectrum: 0.3021796806715429
typography_spectrum: 0.5568495756015182
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2031091747339815
  lightness: 0.30074967606924474
  saturation: 0.39593828725628555
  rhythmicContrast: 0.0051869184244424105
purpose: []
