name: beckybooker
favicon: null
layout_spectrum: 0.3021796806715429
typography_spectrum: 0.5568495756015182
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3b181c'
    - '#753835'
    - '#06050a'
    - '#c69c84'
    - '#bc6f5d'
  brandStrength: 0.3125
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
