favicon: null
name: beckybooker
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5
  brandStrength: 0.4744681
  lightness: 0.9375
  brandColors:
    - '#3b181c'
    - '#753835'
    - '#06050a'
    - '#c69c84'
    - '#bc6f5d'
  rhythmicContrast: 1
typography_spectrum: 0.3914894
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
